# Generated by Django 5.2.7 on 2026-02-23 10:25

import django.db.models.deletion
import gallery_3D_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to=gallery_3D_app.models.user_canvas_directory_path)),
                ('position_choice', models.CharField(choices=[('luogo1', 'Luogo 1'), ('luogo2', 'Luogo 2'), ('luogo3', 'Luogo 3')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scale', models.FloatField(default=1.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
