# Generated by Django 5.2.7 on 2026-02-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='models/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='renders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery_TO_app.model3d')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('hobby', models.CharField(max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='model3d',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='gallery_TO_app.user'),
        ),
        migrations.CreateModel(
            name='GallerySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_color', models.CharField(default='#ffffff', max_length=20)),
                ('light_intensity', models.FloatField(default=1.0)),
                ('floor_texture', models.CharField(default='default_floor.jpg', max_length=100)),
                ('wall_texture', models.CharField(default='default_wall.jpg', max_length=100)),
                ('pedestal_type', models.CharField(default='standard', max_length=50)),
                ('frame_type', models.CharField(default='classic', max_length=50)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery_TO_app.user')),
            ],
        ),
    ]
